# copied from https://github.com/actions/checkout/blob/main/.github/workflows/update-main-version.yml
name: Update Main Version
run-name: Move ${{ github.event.inputs.major_version }} to ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use
        required: true
      major_version:
        type: choice
        description: The major version to update
        options:
          - v1

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        fetch-depth: 0
    - name: Git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Tag new target
      env:
        MAJOR_VERSION: ${{ github.event.inputs.major_version }}
        TARGET: ${{ github.event.inputs.target }}
      run: git tag -f "$MAJOR_VERSION" "$TARGET"
    - name: Push new tag
      env:
        MAJOR_VERSION: ${{ github.event.inputs.major_version }}
      run: git push origin "$MAJOR_VERSION" --force
